### ISSUE TITLE
Password not working.

### ISSUE THREAD

**Issue by Fehuper** [likeproblem/likeproblem.github.io#1]
I think I'm just dumb, but the password seems not to me working, even when I checked that it was the right password at "login.js"

-Muzamel

**Comment by Fehuper** [comment]
I fixed it by just entering https://likeproblem.github.io/index.html into the url bar

**Comment by likeproblem** [comment]
Apparently form submission doesn't redirect page, Im trying to fix it. Using /index.html is not required, just /

**Comment by likeproblem** [comment]
Problem fixed. Panik button can be used for resetting password, and on login it now provides two methods to submit, either enter or button click

**Comment by Fehuper** [comment]
Thanks!
